#ifndef __CEXECSTATUS_H__
#define __CEXECSTATUS_H__

enum class CExecStatus {
    CMD_EXEC_OK,
    CMD_ERR_NOT_SUPPORTED,
    CMD_HW_ERROR_FILE_SYSTEM,
    CMD_ERR_OUT_OF_MEMORY,
    CMD_ERR_BAD_PARAMETER,
    CMD_ERR_BUSY,
    CMD_ERR_ENCRYPTION_VALIDATION,
    CMD_ERR_CRYPTO_FAIL,
    CMD_ERR_DATA_UNAVAILABLE,
    CMD_ERR_BAD_SIZE,
    CMD_ERR_BAD_DATA,
    CMD_ERR_ENROLL,
    CMD_ERR_ENCRYPTION_FAIL,
    CMD_ERR_DECRYPTION_FAIL,
    CMD_ERR_ENROLL_SCORE,
    CMD_ERR_BSP
};

#endif
