#ifndef __HID_RET_VAL_H__
#define __HID_RET_VAL_H__

typedef enum tag_hidres {
    RES_API_OK = 0,
    RES_ERR_NOT_INITIALIZED = -1,
    RES_ERR_DEVICE_DOWN = -2,
    RES_ERR_INTERNAL = -3,
    RES_ERR_UNABLE_TO_CAPTURE = -4,
    RES_ERR_SPOOF_DETECTED = -5,
    RES_ERR_TIMEOUT_EXPIRED = -6,
    RES_ERR_TIMEOUT_LATENT = -7,
    RES_ERR_INVALID_TEMPLATE = -8,
    RES_ERR_KEY_NOT_AVAILABLE = -9,
    RES_ERR_CRYPTO_FAIL = -10,
    RES_ERR_CRYPTO_LOCKED = -11,
    RES_ERR_SIGNATURE_FAIL = -12,
    RES_ERR_INVALID_PARAMETER = -13,
    RES_ERR_READING_DATA = -14,
    RES_ERR_WRITING_DATA = -28,
    RES_ERR_INVALID_DATA = -15,
    RES_ERR_FUNCTION_NOT_SUPPORTED = -16,
    RES_ERR_UNSUPPORTED_FORMAT = -17,
    RES_ERR_FIRMWARE_VERSION = -18,
    RES_ERR_MULTIPLE_DEVICES_FOUND = -19,
    RES_ERR_TAMPER_DETECTED = -20,
    RES_ERR_DATA_UNAVAILABLE = -21,
    RES_ERR_INVALID_SENSOR = -27,
    RES_ERR_MATCH = -28,
    RES_ERR_ENROLL = -29,
    RES_ERR_NO_DEVICES_FOUND = -30,
    RES_ERR_NOT_IMPLEMENTED = -99
}   hidres_t;



#endif

